# --- Environnement & DBus --- #
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY 
exec systemctl --user import-environment XDG_CURRENT_DESKTOP

# --- Services système --- #
exec /usr/libexec/lxqt-policykit-agent 
exec wl-paste --watch cliphist store

# --- Utilitaires --- #
exec gammastep   
exec mako
exec nm-applet --indicator

# --- Tiling --- #
exec autotiling &
