bindsym $mod+Return exec $term
bindsym $mod+e exec $filemanager
bindsym $mod+d exec $menu
bindsym $mod+w exec $texteditor

bindsym XF86HomePage exec $web
bindsym XF86Tools exec aimp
bindsym XF86Mail exec thunderbird
bindsym XF86Messenger exec discord
bindsym Print exec flameshot gui
bindsym XF86Calculator exec galculator

bindsym $mod+Escape exec foot --hold btop
bindsym $mod+q kill
bindsym $mod+f fullscreen
bindsym $mod+r reload
bindsym $mod+space floating toggle

bindsym $mod+a exec ~/.config/rofi/scripts/alarm-window
bindsym $mod+s exec ~/.config/rofi/scripts/system-menu
bindsym $mod+h exec ~/.config/rofi/scripts/show-keybinding
bindsym $mod+c exec ~/.config/rofi/scripts/menu-config
bindsym $mod+v exec cliphist list | rofi -dmenu -p "󰏢 Clipboard" -config .config/rofi/clipboard.rasi | cliphist decode | wl-copy
bindsym $mod+b exec ~/.config/rofi/scripts/web-menu
bindsym $mod+Shift+e exec ~/.config/rofi/scripts/powermenu

bindsym $mod+y exec foot -e yazi
bindsym $mod+i exec foot -e yazi Info
bindsym $mod+p exec pavucontrol
bindsym $mod+n exec nm-connection-editor

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right  
