# --- Appearance & FX --- #

gaps inner 8
default_border pixel 3
default_floating_border pixel 3
default_orientation auto

blur disable
blur_passes 2
blur_radius 3
blur_noise 0.05
corner_radius 8
default_dim_inactive 0.15
shadows enable
shadow_blur_radius 10

for_window [app_id="foot"] blur enable

layer_effects "mako" { 
	blur enable 
	blur_ignore_transparent enable 
}

layer_effects "rofi" { 
	blur enable 
	blur_ignore_transparent enable 
}

# --- Catppuccin Colors --- #

# target                 title     bg    text   indicator  border
client.focused           $blue     $base $text  $blue      $blue
client.focused_inactive  $overlay0 $base $text  $overlay0  $overlay0
client.unfocused         $overlay0 $base $text  $overlay0  $overlay0
client.urgent            $peach	   $base $peach $overlay0  $peach
client.placeholder       $overlay0 $base $text  $overlay0  $overlay0
client.background        $base
