#!/bin/bash

options="BraveSearch\0icon\x1fbrave
DocsMint\0icon\x1fdistributor-logo-linux-mint
Korben\0icon\x1fdistributor-logo-calculate-linux
Maps\0icon\x1fmaps
Movix\0icon\x1fcom.github.artemanufrij.playmyvideos
ProtonDB\0icon\x1fdistributor-logo-steamos
UbuntuWiki\0icon\x1fdistributor-logo-ubuntu
Youtube\0icon\x1fyoutube"

selection=$(echo -e "$options" | rofi -dmenu -show-icons -icon-theme "Papirus" -config ~/.config/rofi/web-menu.rasi)

if [[ -n "$selection" ]]; then
    case "$selection" in
   		"BraveSearch")
   		   	firefox https://search.brave.com 
   		   	 ;;  
   		"DocsMint")
   			firefox https://www.linuxmint.com/documentation.php
   			;;   
  		"Korben")
  			firefox https://korben.info
  			;;          
		"Maps")
			firefox https://www.google.fr/maps
			;;
		"Movix")
			firefox https://movix.bet
			;;
        "ProtonDB")
            firefox https://www.protondb.com
            ;;
		"UbuntuWiki")
			firefox https://doc.ubuntu-fr.org
            ;;
        "Youtube")                    
            firefox https://www.youtube.com
             ;; 
    esac
fi   
